### ISSUE TITLE
Lack of `+someday` tasks throws exception

### ISSUE THREAD

**Issue by bzp99** [abesto/gtd#6]
I only recently switched to GTD with Taskwarrior and have no `+someday` tasks yet. The script fails at `[6/7] Review +someday list`:

```
[5/7] Check last two weeks and next two weeks in calendars done
#--------------------------------------------------------------------------------------------------#
|                                                                                                  |
|   [6/7] Review +someday list                                                                     |
|   Is there anything else that should be on here? Is it time to activate one of these projects?   |
|                                                                                                  |
#--------------------------------------------------------------------------------------------------#
=> task list +someday
No matches.
Error: Command failed: task list +someday
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at task (/home/bp99/node_modules/weekly.js/weekly.js:14:10)
    at Object.reviewSomeday [as run] (/home/bp99/node_modules/weekly.js/weekly.js:160:3)
    at main (/home/bp99/node_modules/weekly.js/weekly.js:235:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 92596,
  stdout: null,
  stderr: null
}
```

I presume this is because `task` returns 1 when no matches are found.

**Comment by bzp99** [comment]
Resolved after merging #7
